// Keep this file in sync with Gradle via the Conveyor plugin.
include "#!./gradlew --console=plain --quiet printConveyorConfig"

include required("/stdlib/jdk/17/openjdk.conf")

app {
  icons = "conveyor_assets/icon/client-icon-*.png"

  vcs-url = "github.com/Qodat/qodat"

  site {
    github {
      oauth-token = ${env.GITHUB_TOKEN}
      pages-branch = "gh-pages"
    }
  }
}

conveyor.compatibility-level = 16
